// Generated by scripts/build-serif-subset.py: the Chinese serif subset that
// public pages preload (declared in public/redesign/fonts.css).
export const SERIF_SUBSET_URL = '/redesign/fonts/9207b5acefb4bf29.woff2';
